version: "3.7"

services:
  numbers-api:
    image: diamol/ch14-numbers-api:v5
    container_name: numbers-api
    environment:
      - Broken=false
      - Logging__LogLevel__Default=Debug
    logging:
      driver: "fluentd"
      options:
        tag: "numbers.api.{{.ImageName}}"

  numbers-web:
    image: diamol/ch14-numbers-web:v5
    container_name: numbers-web
    ports:
      - 8090:80
    logging:
      driver: "fluentd"
      options:
        tag: "numbers.web.{{.ImageName}}"
